# **Ejercicio 1: Crear un arreglo**
#### - Crea un arreglo de números del 0 al 10 e imprime su tipo de datos y su dimensión.
#### - Convierte el arreglo en un arreglo de tipo __float__ y vuelve a imprimirlo.

In [3]:
import numpy as np

arr1 = np.arange(11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
# Tipo de dato
arr1.dtype

dtype('int32')

In [210]:
# Dimension
arr1.ndim

1

In [17]:
# Casteo de tipo int32 a float32
arr1.astype('float32')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

# **Ejercicio 2: Operaciones básicas**
#### - Genera dos arreglos aleatorios de 5 elementos cada uno.
#### - Realiza las siguientes operaciones entre ambos arreglos: suma, resta, multiplicación y división elemento a elemento.
#### -  Calcula el promedio, la mediana y la desviación estándar de uno de los arreglos.

In [23]:
np.random.seed(123)
arr2_1 = np.random.randint(1, 5, size = 5)
print("Array 1:", arr2_1)
arr2_2 = np.random.randint(1, 5, size = 5)
print("Array 2:", arr2_2)

Array 1: [3 2 3 3 1]
Array 2: [3 3 2 4 3]


In [7]:
# Operaciones

suma = arr2_1 + arr2_2
suma

array([6, 5, 5, 7, 4])

In [9]:
resta = arr2_1 - arr2_2
resta

array([ 0, -1,  1, -1, -2])

In [11]:
multi = arr2_1 * arr2_2
multi

array([ 9,  6,  6, 12,  3])

In [13]:
division = arr2_1 / arr2_2
division

array([1.        , 0.66666667, 1.5       , 0.75      , 0.33333333])

In [15]:
# Mediana
np.median(arr2_1)

3.0

In [17]:
#Promedio
np.mean(arr2_1)

2.4

In [39]:
#Desviación estándar
np.std(arr2_1)

0.8

# **Ejercicio 3: Índices y selección**
#### - Crea un arreglo de números del 1 al 25 y redimensionalo en una matriz de 5x5.
#### - Selecciona:
- La primera fila.
- La última columna.
- La submatriz de 3x3 en el centro de la matriz.

In [5]:
arr3 = np.arange(25)
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
arr3 = arr3.reshape(5,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
arr3[1]

array([5, 6, 7, 8, 9])

In [40]:
arr3[0:, 4:]

array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])

In [47]:
arr3[1:4, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

# **Ejercicio 4: Uso de _argmax_ y _argmin_**
#### - Genera un arreglo aleatorio de 10 elementos.
#### - Encuentra el ı́ndice del valor máximo y el ı́ndice del valor mı́nimo.
#### - Cambia el valor máximo a 0 utilizando su ı́ndice.

In [64]:
np.random.seed(123)
arr4 = np.random.randint(1, 10, size = 10)
arr4

array([3, 3, 7, 2, 4, 7, 2, 1, 2, 1])

In [63]:
arr4.argmax()

2

In [65]:
arr4.argmin()

7

In [68]:
arr4[arr4.argmax()] = 0
arr4

array([3, 3, 0, 2, 4, 0, 2, 1, 2, 1])

# **Ejercicio 5: Filtrado y máscaras**
#### - Genera un arreglo de 20 elementos con valores entre -10 y 10.
#### - Crea una máscara para seleccionar solo los valores positivos y otro para los valores negativos.
#### - Imprime ambos subconjuntos de valores.

In [222]:
# Mascara con valores positivos
arr5 = np.arange(-10,10)
arr5

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [232]:
arrpos = (arr5 > 0)
arr5[arrpos]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [234]:
# Mascara con valores negativos
arrneg = (arr5 < 0)
arr5[arrneg]

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

# **Ejercicio 6: Funciones universales**
#### - Crea un arreglo de números del 1 al 10. 
#### - Calcula la raı́z cuadrada, el seno y el logaritmo de cada elemento.
#### - Redondea cada valor del arreglo resultante a 2 decimales.

In [98]:
arr6 = np.arange(1,11)
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
#Raiz cuadrada
np.sqrt(arr6)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [100]:
#Seno
np.sin(arr6)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [101]:
#Logaritmo
np.log(arr6)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

# **Ejercicio 7: Operaciones con matrices**
#### - Crea dos matrices de 3x3 con valores aleatorios.
#### - Realiza las siguientes operaciones entre ambas matrices:
#### * Suma
#### * Multiplicación elemento a elemento
#### * Producto matricial (dot product)
#### - Calcula la transpuesta y la inversa (si existe) de una de las matrices.

In [240]:
np.random.seed(123)
arr7_1 = np.random.randint(1, 9, size = (3,3))
print("Array 1: \n", arr7_1)

arr7_2 = np.random.randint(1,9, size = (3,3))
print("Array 2: \n", arr7_2)

Array 1: 
 [[7 6 7]
 [3 5 3]
 [7 2 4]]
Array 2: 
 [[3 4 2]
 [7 2 1]
 [2 7 8]]


In [242]:
#Suma
arr7_1 + arr7_2

array([[10, 10,  9],
       [10,  7,  4],
       [ 9,  9, 12]])

In [244]:
#Multiplicacion
arr7_1 * arr7_2

array([[21, 24, 14],
       [21, 10,  3],
       [14, 14, 32]])

In [246]:
#Producto punto
np.dot(arr7_1,arr7_2)

array([[77, 89, 76],
       [50, 43, 35],
       [43, 60, 48]])

In [248]:
#Transpuesta
arr7_1.T

array([[7, 3, 7],
       [6, 5, 2],
       [7, 3, 4]])

# **Ejercicio 8: Estadı́sticas**
#### - Genera un arreglo de 100 elementos con números aleatorios enteros entre 1 y 100.
#### - Calcula la media, la mediana, el valor máximo, el valor mı́nimo y la desviación estándar.
#### - Encuentra el percentil 25, 50 y 75 de los datos.

In [250]:
np.random.seed(123)
arr8 = np.random.randint(1, 100, size = 100)
arr8

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48, 74, 33, 47, 97, 26, 84, 79,
       37, 97, 81, 69, 50, 56, 68,  3, 85, 40, 67, 85, 48, 62, 49,  8, 93,
       53, 98, 86, 95, 28, 35, 98, 77, 41,  4, 70, 65, 76, 35, 59, 11, 23,
       78, 19, 16, 28, 31, 53, 71, 27, 81,  7, 15, 76, 55, 72,  2, 44, 59,
       56, 26, 51, 85, 57, 50, 13, 19, 82,  2, 52, 45, 49, 57, 92, 50, 87,
        4, 68, 12, 22, 90, 99,  4, 12,  4, 95,  7, 10, 88, 15, 84])

In [17]:
#Promedio
np.mean(arr8)

53.62

In [15]:
#Mediana
np.median(arr8)

55.5

In [21]:
#Maximo
np.max(arr8)

99

In [23]:
#Minimo
np.min(arr8)

2

In [19]:
#Desviacion estandar
np.std(arr8)

30.344943565609082

### **Percentil:**

In [36]:
# Percentil del 25%
np.percentile(arr8, 25)

26.75

In [38]:
# Percentil del 50%
np.percentile(arr8, 50)

55.5

In [40]:
# Percentil del 75%
np.percentile(arr8, 75)

81.25

# **Ejercicio 9: Concatenación y apilamiento**
#### - Crea dos arreglos de 1x5 y 5x1.
#### - Concáténalos en una sola fila y una sola columna.
#### - Apila ambos arreglos como una matriz 5x2.

In [96]:
arr9_1 = np.arange(1,6)
arr9_2 = np.arange(6,11)
arr9_2.reshape(5,1)

array([[ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [98]:
np.concatenate((arr9_1, arr9_2))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
np.concatenate((arr9_1, arr9_2)).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# **Ejercicio 10: Manipulación de datos en matrices grandes**
#### - Crea una matriz aleatoria de 100x100 con valores entre 0 y 1.
#### - Calcula la suma de todos los elementos de la matriz.
#### - Encuentra el valor máximo de cada fila y almacénalo en un nuevo arreglo.

In [154]:
np.random.seed(123)
arr10 = np.random.randint(2, size = (100,100))
arr10

array([[0, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 1, 0],
       [1, 1, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 1, ..., 1, 0, 1],
       [1, 0, 0, ..., 0, 1, 1]])

In [156]:
np.sum(arr10)

4972

In [162]:
np.amax(arr10, axis = 1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# **Ejercicio 11: Ordenamiento y selección**
#### - Genera un arreglo de 10 números aleatorios entre 0 y 50.
#### - Ordena el arreglo en orden ascendente y descendente.
#### - Selecciona los 3 valores más altos y los 3 valores más bajos del arreglo ordenado.

In [182]:
np.random.seed(123)
arr11 = np.random.randint(0, 51, size = 10)
arr11

array([45,  2, 28, 34, 38, 17, 19, 42, 22, 33])

In [196]:
asc = np.sort(arr11)
asc

array([ 2, 17, 19, 22, 28, 33, 34, 38, 42, 45])

In [198]:
des = -np.sort(-arr11)
des

array([45, 42, 38, 34, 33, 28, 22, 19, 17,  2])

In [204]:
min_arr = asc[:3]
min_arr

array([ 2, 17, 19])

In [206]:
max_arr = des[:3]
max_arr

array([45, 42, 38])